language: node_js
sudo: false

node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "13"

cache:
  directories:
    - node_modules

install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "6" ] ; then nvm use 8 ; fi ;'
  - yarn install
  - yarn build
  - 'if [ "${TRAVIS_NODE_VERSION}" = "6" ] ; then nvm use "${TRAVIS_NODE_VERSION}" && node --version ; fi ;'

script:
  - yarn test
