language: node_js
sudo: false

node_js:
  - "6"
  - "12"

before_install: skip

cache:
  directories:
    - target
    - node_modules

install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "12" ] ; then npm install ; fi ; nvm use "${TRAVIS_NODE_VERSION}";'

script:
  - yarn test

matrix:
  fast_finish: true
  include:
    - node_js: "6"
    - node_js: "12"
